import 'bootstrap/dist/css/bootstrap.min.css'
import '@/styles/style.css'
import Head from 'next/head'
import { Container } from 'react-bootstrap'

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Pokemon</title>
      </Head>
      <main className="home__page-body">
        <Container className="pt-5">
          <Component {...pageProps} />
        </Container>
      </main>
    </>
  )
}
